CREATE SCHEMA IF NOT EXISTS `RemMyLife`;

USE `RemMyLife`;

CREATE TABLE IF NOT EXISTS `userlist`(
	`userID` INT(32) NOT NULL AUTO_INCREMENT,
	`userName` VARCHAR(32) NOT NULL DEFAULT 'FUCK BOY',
	`password` VARCHAR(32) NOT NULL DEFAULT '12345678',
	`nickName` VARCHAR(64) NOT NULL DEFAULT 'SEXY LADY',
	`SEX` ENUM('male','female') NOT NULL DEFAULT 'male',
	`birthday` VARCHAR(32) NOT NULL DEFAULT '1900-01-01',
	`headPortrait` longblob,
	PRIMARY KEY(userID)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `diarylist` (
	`diaryID` INT (32) NOT NULL AUTO_INCREMENT,
	`userID`  INT(32) NOT NULL,
	`TYPE` ENUM('TEXT_DIARY','IMAGE_DIARY','VOICE_DIARY','VEDIO_DIARY') NOT NULL DEFAULT 'TEXT_DIARY',
	`TITLE` VARCHAR (256) NOT NULL DEFAULT 'New Diary',
	`createDate` VARCHAR (32) NOT NULL DEFAULT '',
	`LastSaveDate` VARCHAR (32) NOT NULL DEFAULT '',
	`WEATHER` ENUM('SUNNY','WET','CLOUDY','FOGGY','SNOWY','WINDY') NOT NULL DEFAULT 'SUNNY',
	`SHARED` boolean not null default '0',
	PRIMARY KEY (`diaryID`),
	CONSTRAINT User_Diary FOREIGN KEY diarylist (userID) REFERENCES userlist (userID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `textlist` (
	`diaryID` INT (32) NOT NULL ,
	`TEXT` VARCHAR (4096) ,
	PRIMARY KEY (`diaryID`),
	CONSTRAINT Main_Text FOREIGN KEY textlist (diaryID) REFERENCES diarylist (diaryID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;

CREATE TABLE IF NOT EXISTS `imagelist` (
	`diaryID` INT (32) NOT NULL ,
	`NOTE` VARCHAR (1028) ,
	`ImageData` longblob,
	PRIMARY KEY (`diaryID`),
	CONSTRAINT Main_Image FOREIGN KEY imagelist (diaryID) REFERENCES diarylist (diaryID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;

CREATE TABLE IF NOT EXISTS `voicelist` (
	`diaryID` INT (32) NOT NULL ,
	`NOTE` VARCHAR (1028) ,
	`VoiceData` longblob,
	PRIMARY KEY (`diaryID`),
	CONSTRAINT Main_Voice FOREIGN KEY voicelist (diaryID) REFERENCES diarylist (diaryID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;

CREATE TABLE IF NOT EXISTS `commentlist`(
	`commentID` INT (32) NOT NULL AUTO_INCREMENT,
	`userID` INT(32) NOT NULL,
	`diaryID` INT(32) NOT NULL,
	`content` VARCHAR(256),
	PRIMARY KEY (`commentID`),
	CONSTRAINT Diary_Comment FOREIGN KEY `commentlist` (diaryID) REFERENCES `diarylist` (diaryID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT User_Comment FOREIGN KEY `commentlist` (userID) REFERENCES `userlist` (userID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 ;

